### ISSUE TITLE
Ansible

### ISSUE THREAD

**Issue by denji** [slogsdon/vagrant-phalcon#10]
I have a proposal to move from puppet in ansible

Example code: https://github.com/nganhtuan63/ansible-webstack-php-fpm-nginx-mysql-centos6

**Comment by slogsdon** [comment]
I'm definitely open to a transition to Ansible, as it's something that I've been wanting to learn on my own. It might take a bit before I have the time to put in the work, unless you or someone ese would like to pick this up in the meantime.
