### ISSUE TITLE
Where to find nginx root

### ISSUE THREAD

**Issue by Ichag** [slogsdon/vagrant-phalcon#2]
hi, in the readme the path to nginx root is ./src/Public but i can't find this directory respectively the dir is not used by nginx if i create it.
Did i miss something?

**Comment by slogsdon** [comment]
you might need the directory to exist prior to starting the VM with `vagrant up`. if so, I'll add the directory to the repo by default.

I'm testing this now

**Comment by slogsdon** [comment]
the nginx conf needed to be updated. do a `git pull`, then run `vagrant provision` to correct the nginx config
