### ISSUE TITLE
php-memcached is loaded by memcached is not?

### ISSUE THREAD

**Issue by jsundquist** [slogsdon/vagrant-phalcon#7]
I'm working to use your vagrant configuration within my application which makes use of php5-memcache instead of php5-memached.  It doesn't appear as though you install or start up memcached though.  Any chance you could point me in the direction to get this added in?

**Comment by slogsdon** [comment]
The simplest way is to add a new provision step in your project's `Vagrantfile`. For Ubuntu systems,

``` ruby
config.vm.provision :shell, :inline => "sudo apt-get install -y memcached"
```

would do the trick.  If you're just using the base `Vagrantfile` from this project, yours would then become

``` ruby
Vagrant.configure("2") do |config|
  config.vm.box = "precise64"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"
  config.vm.network :forwarded_port, guest: 80, host: 8081

  # TODO: fix this hack that ensures 'apt-get update' runs before mysql
  # is provisioned with puppet
  config.vm.provision :shell, :inline => "apt-get update --fix-missing"

  # provision our sdev server with the necessary packages and services
  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = "provision/puppet/manifests"
    puppet.module_path = "provision/puppet/modules"
    puppet.manifest_file  = "base.pp"
    puppet.options = ['--verbose']
  end

  # installer/updater for cphalcon
  config.vm.provision :shell do |sh|
    sh.path = "provision/shell/install_phalcon.sh"
  end

  # installer/updater for phalcon-devtools
  config.vm.provision :shell do |sh|
    sh.path = "provision/shell/install_phalcon-devtools.sh"
  end

  config.vm.provision :shell, :inline => "sudo apt-get install -y memcached"
end
```

Once the line is added, running `vagrant provision` in your project directory will run through the provision process again, including your new addition.

More information about provisioning with Vagrant is over in its documenation: http://docs.vagrantup.com/v2/provisioning/index.html.

One downside to this is that configuration is a bit challenging if you're new to Linux administration as everything has to be done manually via the command line (`vagrant ssh`) if you need anything beyond the defaults. A more involved process that would include easier configuration would be to use something like [saz/puppet-memcached](https://github.com/saz/puppet-memcached) to use Puppet manifests to set up and configure memcached on your Vagrant instance.

Hope this helps!

**Comment by jsundquist** [comment]
Awesome thank you @slogsdon.  I'm familiar with linux but just now getting up to speed with how to use vagrant and provisioning.  Still trying to figure out how all of the modules work together and the creation of classes and such. 

Thank you for making a great starter package. Now to figure out how to expand it to fit our needs.
