### ISSUE TITLE
Is phalcon installed by default?

### ISSUE THREAD

**Issue by vimeitor** [slogsdon/vagrant-phalcon#8]
Hello,

I get the following error when trying to run 'phalcon' on the terminal:

PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php5/20121212/phalcon.so' - /usr/lib/php5/20121212/phalcon.so: cannot open shared object file: No such file or directory in Unknown on line 0
ERROR: Phalcon extension isn't installed, follow these instructions to install it: http://docs.phalconphp.com/en/latest/reference/install.html

Furthermore, whatever phalcon-related stuff I put under src/Public doesn't run :/ .

Sincerily,

Adria

**Comment by unisys12** [comment]
@vimeitor I can confirm that Phalcon is not installed. Upon cloning this morning, there is an error  with PCRE during the build of Phalcon that goes a little like this:

``` bash
In file include from /usr/include/php5/ext/spl/spl_iterators.h:27:0, 
from tmp/cphalcon.h3AzcJ/build/64bits/phalcon.c:204:/usr/include/php5/ext/pcre/php_pcre.h:29:18: fatal error: pcre.h: No such file or directory
Compilation terminated.
make: *** [phalcon.lo] Error 1
```

I forked the repo, thinking I was gonna be able to sort this out. And it might very well be something simple, but the more I look into the issue, I am thinking it is going to be a weee bit over my head. So, I am going to hand over the above error msg / info and let someone who knows what they are doing get a handle on this.

**Comment by slogsdon** [comment]
@unisys12 @vimeitor It looks like there's an issue with PCRE not being available which is breaking the installation process. I'll take a look to see what has changed to cause this.

**Comment by slogsdon** [comment]
Yep, according to [this](http://forum.phalconphp.com/discussion/881/compilation-failure-v1-3-0) `v1.3.0` now makes calls to PCRE directly instead of relying on PHP, so there is another package required to be installed before `cphalcon` will compile. I will get a PR to correct for this soon.

**Comment by slogsdon** [comment]
@unisys12  @vimeitor Just pushed a fix for this. Let me know if this doesn't help after a `vagrant destroy && vagrant up`.

**Comment by unisys12** [comment]
@slogsdon Awesome! Built it first thing this morning and works like a charm. Sorry I could not have been more help, but thanks for the great package.

**Comment by vimeitor** [comment]
Hey, thank you to both of you guys for being so fast, especially to @slogsdon for maintaining this!
